// Source copy for the static feature guide. Keep claims aligned with the extension's
// shipped feature catalogue and the domain notes in its private source repository.
export const articles = [
  {
    slug: "visible-capture",
    title: "Capture this screen",
    category: "Capture",
    depth: "Quick note",
    summary: "Keep the viewport exactly as it appears now.",
    lead: "A visible capture is the direct option: one image of the browser viewport, at the display's pixel density. It does not scroll the page or assemble tiles.",
    sections: [
      { title: "Use it for the moment, not the whole document", paragraphs: ["A menu that is open, a hover state, or an error visible right now belongs in This screen. Full page is for everything below the fold; it may move the page and change temporary states while it works."] },
      { title: "A short route through the popup", steps: ["Open ScrollSnapshot on the tab you want.", "Choose This screen and press Capture.", "Review the result, then copy or download it in the format you need."] },
    ],
    note: "Chrome does not allow extensions to capture restricted pages such as chrome:// pages, the Web Store, or its PDF viewer. ScrollSnapshot explains the restriction when it occurs.",
  },
  {
    slug: "full-page",
    title: "One page, top to bottom",
    category: "Capture",
    depth: "Deep guide",
    summary: "Turn a long document into one continuous image.",
    lead: "Full page is for the layout as a whole: a landing page, a report, or a bug that only appears far below the fold. ScrollSnapshot moves through the page, captures the visible pieces, and stitches them together.",
    image: "full-page.png",
    imageAlt: "A full-page website capture in the ScrollSnapshot result viewer",
    imageCaption: "A full-page result, ready to inspect and export.",
    sections: [
      { title: "What happens during the capture", paragraphs: ["Before stitching, ScrollSnapshot moves through the page to let lazy content load. It then restores the page's original scroll position. Fixed elements are handled so a sticky header does not repeat at every seam.", "The standard engine works by scrolling and capturing tiles. Turbo is an optional one-shot engine for pages where that tradeoff makes sense."] },
      { title: "Capture and review", steps: ["Choose Full page in the popup.", "Press Capture and let the page finish moving; the progress view shows the current phase.", "Inspect the result at its real detail before choosing a format or cropping it."] },
      { title: "When one image is too tall", paragraphs: ["Browsers put a ceiling on canvas dimensions. If the page exceeds it, ScrollSnapshot reduces the scale and tells you by how much. Choose Slices when full resolution matters more than having a single file."] },
    ],
    note: "A page with its own scrolling panel needs the Scrolling areas control; ordinary Full page follows the page itself.",
  },
  {
    slug: "numbered-slices",
    title: "Keep a long page at full resolution",
    category: "Capture",
    depth: "Deep guide",
    summary: "A numbered ZIP for pages that outgrow one image.",
    lead: "Slices is the deliberate answer to a page too tall for a single bitmap. Instead of silently shrinking it, ScrollSnapshot saves full-resolution pieces in a ZIP and records where each piece belongs.",
    image: "guide-slices.webp",
    imageAlt: "ScrollSnapshot Slices settings with the Count strategy and overlap control",
    imageCaption: "Choose how a long page is divided before capture.",
    sections: [
      { title: "Choose the cut", paragraphs: ["You can take one piece per screen height, specify a pixel height, or ask for an exact number of parts. Optional overlap repeats a little content at each boundary, useful when a line of text would otherwise sit on a seam."] },
      { title: "What is in the archive", paragraphs: ["The images are numbered in page order and padded so they sort correctly in a file manager. A manifest records their page coordinates. The archive remains useful even after it leaves the extension because the positions are explicit."] },
      { title: "Work with the result", steps: ["Choose Slices, set the height or count, and add overlap if the page has dense text.", "Capture and inspect the slice previews in the result page.", "Download the ZIP, or use Reassemble to make a separate single-image capture for editing."] },
    ],
    note: "Reassembling an extremely tall archive into one image can still require downscaling. The original ZIP keeps the full-resolution pieces.",
  },
  {
    slug: "region",
    title: "Capture only what you mean",
    category: "Capture",
    depth: "Deep guide",
    summary: "Draw, move, resize, or type a precise region.",
    lead: "A region capture starts with a boundary you control. Draw a rectangle on the page, trace a freeform shape, or enter exact page coordinates when the target is below the fold.",
    image: "region.png",
    imageAlt: "An editable region selection over a web page",
    imageCaption: "The selection remains editable before the capture.",
    sections: [
      { title: "The selection is still yours after the drag", paragraphs: ["A drawn rectangle can be moved and resized before confirmation. Enter confirms; Escape cancels without keeping a capture. The overlay measures against the visible viewport, while typed coordinates are measured from the document's top-left corner."] },
      { title: "Choose the shape", paragraphs: ["A rectangle keeps its full box. A freeform lasso makes the area outside the path transparent, so the result uses a format that can preserve transparency. A region taller than one screen can be stitched like a full-page capture."] },
      { title: "A reliable sequence", steps: ["Choose Region and select Draw or Coordinates.", "Set the boundary, then adjust it if needed.", "Confirm the selection and inspect the captured pixels before exporting."] },
    ],
    note: "If the target is a stable page element, Capture by selector can be more repeatable than typed pixel coordinates.",
  },
  {
    slug: "batch-capture",
    title: "Capture a queue of pages",
    category: "Capture",
    depth: "Deep guide",
    summary: "Current-window tabs or up to 50 pasted addresses.",
    lead: "Batch belongs in Settings because it is a queue, not a single click on the current tab. It can capture the ordinary web tabs in the current window or a list of up to 50 addresses you paste.",
    image: "guide-batch.webp",
    imageAlt: "ScrollSnapshot Batch settings showing three example web addresses",
    imageCaption: "One address per line; each becomes its own full-page capture.",
    sections: [
      { title: "One page at a time", paragraphs: ["The worker runs each full-page capture in order and keeps a result for every successful page. A failed address does not stop the rest. Temporary tabs opened from pasted addresses are closed afterward; tabs that were already open are left alone, and the starting tab is restored."] },
      { title: "Before you start", paragraphs: ["Capture history must be on, or each result would replace the previous one. Batch uses your capture defaults but skips interactive pickers and delays; a queue cannot pause for a separate choice on every page."] },
      { title: "Run a batch", steps: ["Open Settings and find Batch capture.", "Choose current-window tabs or paste a web address on each line.", "Start the queue, then review the per-page results and failures in local history."] },
    ],
    note: "Batch accepts ordinary HTTP and HTTPS pages. Browser pages, extension pages, and non-web schemes are skipped or rejected.",
  },
  {
    slug: "scrolling-areas",
    title: "The page is not always what scrolls",
    category: "Capture",
    depth: "Deep guide",
    summary: "Capture a chat, mail list, or panel with its own scroll.",
    lead: "Some web apps keep the document still while a panel carries hundreds of rows. An ordinary full-page capture sees one screenful. Scrolling areas tells ScrollSnapshot which inner panel to follow.",
    sections: [
      { title: "Pick the actual container", paragraphs: ["Turn on Capture a scrolling area under Full page, then point at the panel. The picker highlights an element that really scrolls; the up arrow widens to an enclosing scrolling element. Escape cancels without capturing."] },
      { title: "After the pick", paragraphs: ["The standard engine scrolls the selected element vertically, captures its content, and restores both the panel and the page to their starting positions. It does not resize the app to force more content into view."] },
      { title: "A useful check", steps: ["Open the app at the panel you need.", "Choose Full page and turn on Capture a scrolling area.", "Pick the panel, capture, and check that its last row appears in the result."] },
    ],
    note: "Scrolling-area capture uses the standard stitching engine. Turbo falls back with a notice for this workflow.",
  },
  {
    slug: "turbo-engine",
    title: "A faster route through a full page",
    category: "Capture",
    depth: "Focused guide",
    summary: "An optional one-shot capture engine with a visible Chrome banner.",
    lead: "Turbo uses Chrome's DevTools protocol to capture a full page in one shot. It can avoid some scrolling artifacts, but Chrome displays a debugging banner while the extension is attached.",
    image: "guide-turbo.webp",
    imageAlt: "ScrollSnapshot Capture settings with the Standard and Turbo engine choices",
    imageCaption: "Turbo is an explicit engine choice in Capture settings.",
    sections: [
      { title: "Why it is optional", paragraphs: ["The standard engine is the default because it works without attaching a debugger. Turbo is a deliberate choice for a difficult page or a time-sensitive full-page capture. Chrome's banner is browser UI; ScrollSnapshot does not hide it."] },
      { title: "Use it deliberately", steps: ["Choose Full page in the popup and switch the engine to Turbo.", "Capture the page and leave Chrome's banner in place until it finishes.", "Review the result and any fallback notice before exporting."] },
    ],
    note: "If Chrome cannot attach the debugger, ScrollSnapshot falls back to the standard engine and explains the change.",
  },
  {
    slug: "chosen-viewport-width",
    title: "Check a page at another width",
    category: "Capture",
    depth: "Focused guide",
    summary: "A responsive full-page capture without resizing your window.",
    lead: "Chosen viewport width is a Turbo option for responsive QA. It asks the page to reflow at a mobile, tablet, laptop, or custom CSS width before the full-page capture is measured.",
    sections: [
      { title: "Width changes the layout", paragraphs: ["A different width can move navigation, stack cards, and change the page's total height. ScrollSnapshot measures after the reflow, keeps the display's real pixel density, and clears the temporary override when the capture ends."] },
      { title: "Where to find it", steps: ["Enable Chosen viewport width on the Features page if it is hidden.", "Choose Full page and Turbo, then select a preset or type a custom width.", "Capture and check the result for a warning if Turbo could not apply the width."] },
    ],
    note: "This applies only to Turbo full-page captures. This screen, Region, Slices, and the standard engine use the actual window width.",
  },
  {
    slug: "start-from-scroll",
    title: "Start from where you are",
    category: "Capture",
    depth: "Quick note",
    summary: "Begin a full-page capture below the top of a document.",
    lead: "When the useful section begins halfway down a page, Start from where you are begins the full-page capture at the current scroll position instead of going back to the top.",
    sections: [
      { title: "A practical moment", paragraphs: ["Use it after navigating to a chapter, a result section, or a long thread whose opening is irrelevant. The result still follows the page downward from the position you chose."] },
      { title: "Use the current position", steps: ["Scroll to the first content you want included.", "Choose Full page and turn on Start from where you are.", "Capture, then check the first row of the result before saving."] },
    ],
    note: "Leave this off when you need an image that begins at the document's top.",
  },
  {
    slug: "delay-before-capture",
    title: "Give the page a few seconds",
    category: "Capture",
    depth: "Quick note",
    summary: "Open a menu or hover state after pressing Capture.",
    lead: "Some UI disappears as soon as you move to the extension popup. A capture delay gives you a short countdown to return to the page and open the state you want to show.",
    sections: [
      { title: "The countdown comes first", paragraphs: ["ScrollSnapshot waits before preparing or moving the page, so the menu or hover state you create during the countdown is not disturbed early. The worker owns the timer even after the popup closes."] },
      { title: "Set up the moment", steps: ["Enable Delay before capture on the Features page if it is hidden.", "Choose the delay in the popup and press Capture.", "Return to the page, open the menu or hover state, and let the countdown finish."] },
    ],
    note: "Cancel during the countdown stops before the page is touched.",
  },
  {
    slug: "leave-out-elements",
    title: "Leave the obstruction out",
    category: "Capture",
    depth: "Quick note",
    summary: "Temporarily omit a banner, bubble, or other page element.",
    lead: "A cookie banner or chat bubble can cover the content you came to capture. Leave out elements lets you point to those page elements before the screenshot is taken.",
    sections: [
      { title: "What changes", paragraphs: ["The chosen element is temporarily removed from the page layout, so content beneath it can close the gap. ScrollSnapshot restores it when the capture finishes, fails, or is cancelled. Text extraction also follows the page without the omitted element."] },
      { title: "Use it before selecting a region", steps: ["Enable Leave out elements on the Features page if needed.", "Start the capture and click the obstructing element in the picker.", "Complete the capture and inspect the content that was revealed."] },
    ],
    note: "Use this for an obstruction, not for editing private pixels. Redact a finished capture when information must be covered in the saved file.",
  },
  {
    slug: "capture-by-selector",
    title: "Name the element, capture its box",
    category: "Capture",
    depth: "Focused guide",
    summary: "Use a CSS selector, XPath, or a direct element pick.",
    lead: "When the target is a specific component, naming it can be steadier than measuring pixels. Region's Selector choice resolves a CSS selector or XPath expression and captures the first matching element's box.",
    sections: [
      { title: "Two ways to choose", paragraphs: ["Type a selector in the popup, or use the target control to click the element on the page. The click picker highlights the target; the up and down arrows move between it and its parent. A clicked element confirms the capture in one step."] },
      { title: "Keep the target unambiguous", steps: ["Choose Region, then Selector.", "Enter a specific CSS selector or XPath expression, or pick the element directly.", "Inspect the result to confirm the first match was the one you intended."] },
    ],
    note: "Invalid selectors, missing matches, and zero-size elements are refused with an explanation. If the page reflows, an element target is often more reliable than typed coordinates.",
  },
  {
    slug: "crop",
    title: "Decide what the file keeps",
    category: "Edit",
    depth: "Quick note",
    summary: "Trim a finished capture before copying or downloading.",
    lead: "Crop removes pixels outside a boundary after you have seen the capture. It is useful when the page needed a broad capture but the file you share should show only one part.",
    sections: [
      { title: "Work on the result", paragraphs: ["Draw the crop over the displayed image. ScrollSnapshot maps that selection back to the image's source pixels, even when a tall screenshot is scaled down to fit the screen. Format changes afterward still use the cropped image."] },
      { title: "A clean finish", steps: ["Open the finished capture and choose Crop.", "Draw the boundary and apply it.", "Check the edges, then copy or download the result."] },
    ],
    note: "Undo crop restores the previous image. Crop is for ordinary image captures, not a Slices ZIP.",
  },
  {
    slug: "redact",
    title: "Cover what should not travel",
    category: "Edit",
    depth: "Deep guide",
    summary: "Black out or pixelate details in the saved image.",
    lead: "Redaction changes the image itself. Use it for a name, token, address, or other detail that should not appear in the exported capture.",
    image: "editor.png",
    imageAlt: "ScrollSnapshot editor with redaction and annotation controls",
    imageCaption: "Marks are applied to the image before export.",
    sections: [
      { title: "Two different marks", paragraphs: ["Black out fills the selected area with opaque black. Pixelate replaces it with coarse blocks. Both are applied to the source image, not merely painted over the browser preview."] },
      { title: "Check before you send", steps: ["Open the result and choose Edit, then Redact.", "Draw over each sensitive area, zooming in if the edge is close to text you want to keep.", "Apply the edit and inspect the exported image, not only the editing overlay."] },
      { title: "Text beside the image", paragraphs: ["A Region capture may include text read from the page. Once you apply a redaction, ScrollSnapshot withholds that extracted text so it cannot reveal words hidden in the image. Undo edits brings it back."] },
    ],
    note: "An arrow or highlight points at content; it does not hide it. Use Redact when the pixels themselves must be obscured.",
  },
  {
    slug: "annotate",
    title: "Make the important part obvious",
    category: "Edit",
    depth: "Focused guide",
    summary: "Boxes, arrows, highlights, text, and pen marks.",
    lead: "Annotation turns a capture into an explanation. Draw a box around a faulty control, point an arrow at the exact state, or put a brief label where a reader will look first.",
    image: "editor.png",
    imageAlt: "ScrollSnapshot editor showing marks over a captured page",
    imageCaption: "The marks preview over the capture before they are applied.",
    sections: [
      { title: "Marks stay aligned with the image", paragraphs: ["ScrollSnapshot stores mark positions in the image's own pixels. A tall screenshot may be displayed small on screen, but a box or arrow is mapped back to the full image before export."] },
      { title: "Build a readable note", steps: ["Open Edit and choose a tool: Box, Arrow, Highlight, Text, or Pen.", "Use one colour and a small number of marks to establish the reading order.", "Apply the marks, then review the final file at the size your recipient will see."] },
    ],
    note: "Redactions are painted before other marks, so a later arrow cannot uncover information you covered.",
  },
  {
    slug: "step-numbers",
    title: "Put the steps on the page",
    category: "Edit",
    depth: "Quick note",
    summary: "Numbered markers for a sequence in one screenshot.",
    lead: "A single image can hold a whole instruction when the order is visible. Step numbers places numbered circles where the reader should look, in the order you add them.",
    sections: [
      { title: "The numbers follow the marks", paragraphs: ["A marker's number is its place among the step markers. Delete the first of three and the remaining two renumber automatically; undo restores the sequence. That keeps you from manually relabeling a screenshot after one correction."] },
      { title: "Keep a sequence short", steps: ["Enable Step numbers on the Features page if it is hidden.", "Open Edit and place markers in reading order.", "Apply the marks and check that every number is visible at the final viewing size."] },
    ],
    note: "A separate image per step may be clearer when the page changes state between actions.",
  },
  {
    slug: "style-presets",
    title: "Keep your annotation style close",
    category: "Edit",
    depth: "Quick note",
    summary: "Save a colour, stroke, and text size for reuse.",
    lead: "Style presets remove repeated setup when you annotate many captures in the same way. Save the mark style you are using and recall it with one click on the next image.",
    sections: [
      { title: "What a preset remembers", paragraphs: ["A preset stores colour, stroke weight, and text size. It does not store a tool or a redaction style. ScrollSnapshot keeps up to three presets, with the most recently used first."] },
      { title: "Use a repeatable mark", steps: ["Enable Style presets on the Features page if it is hidden.", "Set a mark's colour, stroke, and text size in the editor.", "Save the style from the preset control and choose it on later captures."] },
    ],
    note: "Presets help consistency; they do not change the pixels until you apply a mark.",
  },
  {
    slug: "image-formats",
    title: "Choose the file after seeing the image",
    category: "Output",
    depth: "Focused guide",
    summary: "PNG, JPEG, WebP, copy, download, and output scale.",
    lead: "A screenshot's best format depends on what it contains and where it is going. ScrollSnapshot lets you choose after capture, without photographing the page again.",
    sections: [
      { title: "Three image choices", paragraphs: ["PNG is lossless and keeps transparency. JPEG is smaller for photographic pages but has no transparency. WebP can be compact while preserving transparency. The result page re-encodes the current image when you switch formats."] },
      { title: "Size and destination", paragraphs: ["The Scale control can export at 100, 75, 50, or 25 percent without shrinking the stored source. Download keeps the chosen file format. Copy sends PNG because the browser clipboard accepts PNG image data for this workflow."] },
      { title: "A practical check", steps: ["Inspect the finished capture and choose a format.", "Choose a smaller output scale only if the recipient does not need full detail.", "Download or copy, then check the result at its intended viewing size."] },
    ],
    note: "For a document that needs paper pages, use PDF export instead of stretching an image into a print layout later.",
  },
  {
    slug: "pdf-export",
    title: "A screenshot that fits the document",
    category: "Output",
    depth: "Focused guide",
    summary: "One tall PDF page or paginated A4 and Letter output.",
    lead: "PDF export is for a capture that needs to be filed, printed, or reviewed as a document. Choose one tall page, or let ScrollSnapshot divide the image across A4 or Letter pages.",
    sections: [
      { title: "Paper is a different boundary", paragraphs: ["Tall keeps the captured page as one PDF page. A4 and Letter add paper-sized pages with margins. For supported captures, ScrollSnapshot uses line positions from the page to place breaks between visible lines where it can, rather than cutting through a row of text."] },
      { title: "Export from the finished image", steps: ["Capture and make any crop or edits first.", "Choose PDF in the result page, then Tall, A4, or Letter in the Page control.", "Download and review the page breaks before sharing or printing."] },
    ],
    note: "PDF is made from the captured pixels. It is an image document, not a reflowed copy of the web page's text.",
  },
  {
    slug: "capture-history",
    title: "Find the capture you already made",
    category: "Output",
    depth: "Focused guide",
    summary: "A searchable, local record of recent captures.",
    lead: "Capture history keeps recent results on your device so a useful image does not vanish when its result tab closes. Browse thumbnails, search by page title, filter by mode, or mark a favorite.",
    image: "private.png",
    imageAlt: "ScrollSnapshot's local capture history interface",
    imageCaption: "Captures stay on the device where they were made.",
    sections: [
      { title: "Retention is a choice", paragraphs: ["Settings controls how many captures to keep and whether older ones expire. Turning Capture history off prunes the store to the current result; the next capture replaces it. Batch requires history on so every successful page survives its queue."] },
      { title: "Retrieve or remove", steps: ["Open History from the popup or Settings.", "Search for a title or filter by Visible, Full page, Slices, or Region.", "Open, download, favorite, or delete a capture. Clear history asks before removing everything."] },
    ],
    note: "Captures and their page details stay on this device. Some extension settings may use Chrome Sync between your own signed-in browsers; the images do not go to a ScrollSnapshot server.",
  },
  {
    slug: "reassemble-slices",
    title: "Bring the pieces back together",
    category: "Output",
    depth: "Focused guide",
    summary: "Make a single editable image from a ScrollSnapshot ZIP.",
    lead: "Slices keeps long pages at full resolution, but sometimes you also need one image for cropping or annotation. Reassemble reads the archive's page coordinates and builds a new full-page result.",
    sections: [
      { title: "Two starting points", paragraphs: ["Open a Slices result and choose Reassemble into one image, or use Open slices ZIP from the History page for an archive saved earlier. ScrollSnapshot checks that the ZIP contains its own Slices manifest before building anything."] },
      { title: "The original stays useful", paragraphs: ["The combined page is a new capture. The original Slices record remains available when you reassemble from history. If the combined image exceeds the browser's canvas ceiling, the result may be downscaled and will say so; the ZIP's pieces retain their resolution."] },
      { title: "A quick route", steps: ["Open the Slices result or a saved ScrollSnapshot ZIP.", "Choose Reassemble into one image.", "Inspect the new result, then crop, edit, or download it."] },
    ],
    note: "An arbitrary ZIP from another screenshot tool is refused; the page coordinates in ScrollSnapshot's manifest are required.",
  },
  {
    slug: "colour-picker",
    title: "Take the colour from the page",
    category: "Tools",
    depth: "Quick note",
    summary: "A pixel loupe that copies the hex value you choose.",
    lead: "The colour picker is for the one pixel you actually mean. Point at the page, inspect the enlarged area and hex value, then click to copy it.",
    sections: [
      { title: "Why it lives on the page", paragraphs: ["The extension popup closes when focus moves to the page, so the picker itself handles the copy. It samples the device pixel under the pointer instead of inventing an average colour from a high-density display."] },
      { title: "Choose a pixel", steps: ["Start Pick a colour from the popup.", "Move the loupe over the pixel you need and read the displayed hex.", "Click to copy it, or press Escape to leave without choosing."] },
    ],
    note: "Use the colour palette on a finished capture when you want the dominant colours, rather than one exact pixel.",
  },
  {
    slug: "text-reader",
    title: "Read the words under a region",
    category: "Tools",
    depth: "Focused guide",
    summary: "Copy page text without guessing at it with OCR.",
    lead: "A screenshot is pixels, but a web page also has text nodes. For a region capture, ScrollSnapshot reads the page text under the selected area and offers it beside the image.",
    sections: [
      { title: "The browser has the source", paragraphs: ["The reader preserves document order and line structure. It can read the actual characters, including non-Latin scripts, without making an OCR guess. Hidden page elements are excluded because they were not visible in the capture."] },
      { title: "Use both outputs", steps: ["Capture a region that includes the words you need.", "Inspect the image and the text panel in the result page.", "Copy the text separately when an editable quote is more useful than pixels."] },
    ],
    note: "Words baked into an image or a cross-origin frame are not page text the extension can read. A redaction withholds extracted text so it cannot expose what the image covers.",
  },
  {
    slug: "colour-palette",
    title: "See the colours that dominate",
    category: "Tools",
    depth: "Quick note",
    summary: "A ranked palette drawn from the finished capture.",
    lead: "The colour palette is a quick read of the finished image: a small set of dominant colours, each with its share of the visible pixels and a hex value you can copy.",
    sections: [
      { title: "What the shares mean", paragraphs: ["ScrollSnapshot samples large images, groups nearby values, and ranks the resulting colours by share. A nearly solid screenshot may show one colour instead of padding the list with invented swatches. Transparent pixels are left out of the count."] },
      { title: "Use it as a starting point", steps: ["Finish a capture and open its result page.", "Read the palette beneath the image.", "Click a swatch to copy its hex, then check a specific pixel with the picker if precision matters."] },
    ],
    note: "A dominant palette summarizes an image; it does not replace the colour picker for an exact point.",
  },
];
